import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";

// GET: List reports for a volunteer
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const reports = await prisma.volunteerReport.findMany({
      where: { volunteerId: id },
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json(reports);
  } catch (error) {
    console.error("Failed to list reports:", error);
    return NextResponse.json(
      { error: "보고서 목록을 불러오는데 실패했습니다." },
      { status: 500 }
    );
  }
}

// POST: Generate report (set autoGenerated=true)
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await request.json();
    const { title, period, content, filePath } = body;

    if (!title || !period) {
      return NextResponse.json(
        { error: "title과 period는 필수 항목입니다." },
        { status: 400 }
      );
    }

    const report = await prisma.volunteerReport.create({
      data: {
        volunteerId: id,
        title,
        period,
        content,
        filePath,
        autoGenerated: true,
      },
    });

    return NextResponse.json(report, { status: 201 });
  } catch (error) {
    console.error("Failed to generate report:", error);
    return NextResponse.json(
      { error: "보고서 생성에 실패했습니다." },
      { status: 500 }
    );
  }
}
